name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            py-version: 3.7
          - os: macos-latest
            py-version: 3.8
          - os: windows-latest
            py-version: 3.9

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run tests
      run: python -m unittest discover
