name: Installing Python
'on':
  - push
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        py-version:
          - 3.7
          - 3.8
          - 3.9
        exclude: #added
         - os: macos-latest 
           py-version: 3.7
         - os: macos-latest
           py-version: 3.8
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.py-version }}'
